# Generated by Django 4.1.3 on 2022-12-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IstaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Login')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
            ],
            options={
                'verbose_name': 'Инста логин',
                'verbose_name_plural': 'Инста логины',
            },
        ),
    ]
